<!-- About Section -->
<section id="about" class="content-section text-center">
      <div class="container2">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <h1>About Me</h1>
            <img src="public/img/donut2.png">
            <h2>Patcharawat  Sukrak</h2>
            <img src="public/img/cmu.png" width="300 " height="300">
            <p>Entaneer at Chiang Mai University</p>
            <p>CPE25</p>
            <p>590610643</p>

            <p>You can contact me on
              <a href="https://www.facebook.com/profile.php?id=100008681733666">Facebook</a></p>
          </div>
        </div>
      </div>
      <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
    </section>