<div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <br><br><br><br><br><br>
            <h1 class="section-heading text-uppercase">Plese  login First. </h1>
            <a href="authen" class="btn btn-primary"> Login </a>
            <a href="<?php echo $this->url->getBaseUri(); ?>" class="btn btn-warning">Back</a>
          </div>
        </div>
      </div>

   