<div class="container">
        
        <img class="img-fluid mb-5 d-block mx-auto" src="<?php echo $this->url->getBaseUri(); ?>public/img/Welcome-RED.png" width="700" height="1000" alt="">
        <img class="img-fluid mb-5 d-block mx-auto" src="<?php echo $this->url->getBaseUri(); ?>public/img/ul_goku.png" width="1000" height="1000" alt="">
        <!-- <img src="public/img/ul_goku.png" width="1000" height="1000"> -->
        <!-- <h1 class="text-uppercase mb-0  text-center">Start Bootstrap</h1> -->
</div>